name: EasyRepairItems
main: GodWeedZao\EasyRepairItems\Main
version: 1.0.0
api: 3.0.0
load: POSTWORLD
author: GodWeedZao
description: Repair damaged items in hand.
depend: [EconomyAPI]
commands:
  repair:
    describtion: "Repair Damaged Item In Hand"
permissions:
  EasyRepairItems.command:
    default: op
