#Xp: set it to true, if you want to players repair their Items with their Xp Level (Xp Payment)
XP: true
#Money: set it to true if you want to players repair their Items with their Money (EconomyAPI)
MONEY: false
#if you want to send Title to player, when player Repair Item in hand Succes.
Send-Title-Success: true
#if you set Money to true, you should set a price for item repairing.
Repair-Item-Price-Money: 1000
#if you set Xp to true, you should set a price for items repairing.
Repair-Item-Price-Xp: 3
#if player want to repair an enchanted item, and if you set Money to true, set a price for repairing items.
Repair-Enchanted-Item-Price-Money: 10000
#if player want to repair an enchanted item, and if you set Xp to true, set a price for repairing items.
Repair-Enchanted-Item-Price-Xp: 9
#Cooldown: set is to true, if you want to make limit for using /repair, or set it to false, without limit.
Cooldown: true
#Cooldown-Time is a limit ps (Per Second) for Repairing Items
Cooldown-Time: 30
#Success message will show to player after Repairing success Items.
Success: "§l§aSuccess"
#Done, Enjoy it.
#for connect me: t.me/ErrorByNight
